# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(21de15f8-7720-4116-95ea-9a1751381acc)'
    subscriptionId: '21de15f8-7720-4116-95ea-9a1751381acc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Testgroup1'
    location: 'Poland Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/eTagak/AzureDevOps/blob/main/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'pipeline_test'